### ISSUE TITLE
Clicking the chiclet on OKTA does not automatically sign me in

### ISSUE THREAD

**Issue by cquinn930** [AzMoo/django-okta-auth#12]
I have the setup ready and I can see the data and session keys. I am not able to automatically sign into the app from OKTA. it always asks me for a u/p/mfa. Is there a config setting or something I missed? Please let me know what configs or setup you need to see?

**Comment by AzMoo** [comment]
It's not a configuration issue on the client side, it's because you're not staying logged into Okta.
