### ISSUE TITLE
Limit access to users belonging to specific group.

### ISSUE THREAD

**Issue by platonfloria** [AzMoo/django-okta-auth#13]
I'm facing an issue where I don't want all okta users within my organisation to have access to a specific app.
Currently it is impossible to control access to apps by assigning okta users to relevant groups.

**Comment by platonfloria** [comment]
https://github.com/AzMoo/django-okta-auth/pull/16

**Comment by AzMoo** [comment]
Hey I know this was from a ridiculously long time ago, and I'm very sorry for the slow reply, but I'm not sure I understand why you would need this. If you don't want your users to have access to the application then you shouldn't assign them to the application within Okta.

I'm going to close it for now but let me know if I've missed something.
