### ISSUE TITLE
Superuser group configuration 

### ISSUE THREAD

**Issue by andrewbelo** [AzMoo/django-okta-auth#7]
I am having trouble configuring admin page permissions for users. 
As I understand it, the **SUPERUSER_GROUP** is responsible for this functionality. But, after adding _groups_ to the **SCOPE**, I am receiving an error saying: _One or more scopes are not configured for the authorization server resource._.

**Comment by AzMoo** [comment]
This is an error returned by Okta if your application or authorization server is not configured properly. 

You probably don't have one of the default scopes enabled. By default you require: "openid profile email offline_access". You can see which scopes are enabled in your authorization server settings in Okta. It's under the API menu heading.

**Comment by andrewbelo** [comment]
Yes, all of them are enabled. But, when I try to use "groups" scope it returns this error. I am not sure if adding this scope manually is enough.
![Screenshot from 2021-02-05 10-47-40](https://user-images.githubusercontent.com/31931886/107010958-afb0e980-679f-11eb-99c7-487db272d76b.png)

**Comment by AzMoo** [comment]
Can you check out this forum thread and see how you go? https://devforum.okta.com/t/no-groups-scope-in-the-console-for-the-default-authorisation-server/5573

**Comment by AzMoo** [comment]
I'm closing this due to the lack of response.
